# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Windows Build

on:
  pull_request:

jobs:
  maven-build:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Install Apache Maven Daemon
          id: install-mvnd
          uses: ./.github/actions/install-mvnd
          with:
            version: '1.0.2'
            file-version-suffix: ''
            cache: 'true'
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2 -Dmaven.wagon.http.pool=true
        run: ${{ steps.install-mvnd.outputs.mvnd-dir }}/mvnd -V -B -PskipBrokenTests test
